# Generated by Django 5.1.3 on 2024-12-09 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reports',
            name='discription',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reports',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
