# Generated by Django 5.1.3 on 2024-12-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reports_date_alter_reports_discription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='image',
            field=models.ImageField(blank=True, default='test.jpg', upload_to=''),
        ),
    ]
