# Generated by Django 5.1.3 on 2024-12-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_reports_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='image',
        ),
        migrations.AddField(
            model_name='reports',
            name='report_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
