# Generated by Django 5.1.3 on 2024-12-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_reports_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='author',
        ),
    ]
